### ISSUE TITLE
how to swap hair also?

### ISSUE THREAD

**Issue by LoganRebecca** [hxngiee/DiffFace#14]
I modify the parsing index with [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,17],including 17 hair, however, the results seems no diff, can you help me with that?

**Comment by hxngiee** [comment]
Since face swap is not a task that changes the hair of the target image, the hair remains unchanged.  However, the attributes of the source can be reflected during the process of injecting the source's identity (Please refer to the intermediate state of the samples created in the Results folder)

Currently, the background of the target image is being forcibly blended. Try adding --no_enforce_background options to your command.

**Comment by LoganRebecca** [comment]
Ok, I'll give it a try, thanks for the quick reply!
